const quotes = [
    "Kamu itu konstan di hidupku, nggak pernah berubah jadi kurang penting.",
    "Aku mungkin nggak jago matematika, tapi menghitung rasa sayangku ke kamu itu tak hingga.",
    "Kamu itu variabel paling penting di hidupku.",
    "Kalau hidupku fungsi, maka kamu itu domain utamanya.",
    "Peluang aku suka kamu = 100%.",
    "Kamu bikin hati aku berdetak kayak deret berpola: makin lama makin cepat.",
    "Kalau kamu sudut, kamu itu sudut favoritku.",
    "Kamu dan aku cocok kayak dua garis yang akhirnya ketemu.",
    "Kamu itu solusi dari semua masalahku.",
    "Bahagia = aku + kamu.",
    "Dari semua bilangan, cuma kamu yang spesial di mataku.",
    "Kalau cinta itu vektor, arahnya selalu menuju kamu.",
    "Kamu itu pusat koordinat hatiku.",
    "Kalau aku grafik, kamu itu titik maksimum kebahagiaanku.",
    "Kamu itu jawaban yang tidak pernah ingin aku salah hitung.",
    "Kamu bikin hidupku teratur kayak pola geometri.",
    "Kalau aku milih antara 1–1.000.000, tetap kamu nomor satu.",
    "Kamu itu limit dari semua harapanku.",
    "Kamu itu solusi yang paling sederhana dari hati yang rumit.",
    "Kamu bikin semua logikaku hilang.",
    "Kamu itu konstanta yang bikin hidupku stabil.",
    "Hati aku kayak persamaan, dan kamu itu nilai x-nya.",
    "Dari sekian banyak himpunan pilihan, aku tetap memilih kamu.",
    "Kamu itu fungsi monoton naik: makin hari makin aku suka.",
    "Hatiku kalau lihat kamu langsung bikin grafik naik tajam.",
    "Kamu itu probabilitas yang selalu aku pilih.",
    "Kamu bikin hidupku lengkap kayak persamaan sempurna.",
    "Kamu itu pembuktian kalau cinta itu nyata.",
    "Kamu itu faktor yang bikin hidupku punya makna.",
    "Kamu itu satu-satunya bilangan yang pas buatku.",
    "Aku cepat jatuh ke kamu.",
    "Kamu kayak segitiga, stabil dan kokoh.",
    "Kamu itu jawaban benar yang selalu aku cari.",
    "Kamu itu titik temu semua keinginanku.",
    "Kamu bikin aku tambah bahagia tiap hari.",
    "Kalau aku fungsi, kamu itu input terbaikku.",
    "Kamu itu bilangan positif yang menghapus semua negatif di hidupku.",
    "Kamu itu pusat rotasi hatiku.",
    "Kebahagiaanku meningkat drastis sejak ada kamu.",
    "Kamu itu jawaban tanpa harus aku pikir terlalu rumit.",
    "Kalau cinta itu persamaan, kamu solusinya.",
    "Kamu bukti kalau cinta bisa dihitung dari rasa.",
    "Kamu itu pengali kebahagiaanku.",
    "Kamu itu satu-satunya nilai yang nggak bisa aku ubah.",
    "Kamu bikin aku yakin kalau 1 + 1 = kita.",
    "Kamu itu fungsi bijektif: cuma satu kamu, aku cuma buat kamu.",
    "Kamu bikin detak jantungku naik kayak grafik eksponensial.",
    "Kamu itu pilihan optimum dalam hidupku.",
    "Kamu itu jawaban yang tidak bisa aku eliminasi.",
    "Kamu itu pola tetap di hariku.",
    "Kamu itu median kebahagiaanku.",
    "Kamu itu titik pusat semua rencanaku.",
    "Kamu itu peluang terbaik yang pernah aku dapat.",
    "Kamu bikin hatiku stabil kayak sudut 90°.",
    "Kamu itu bilangan prima: unik dan nggak bisa dibandingkan.",
    "Kamu bikin hidupku lengkap tanpa sisa.",
    "Kamu itu determinan kebahagiaanku.",
    "Kamu itu titik potong antara harapan dan kenyataan.",
    "Kamu bikin hidupku indah kayak parabola terbuka ke atas.",
    "Kamu itu variabel bebas yang selalu aku pilih.",
    "Kamu itu nilai maksimum di hidupku.",
    "Kamu itu output paling indah.",
    "Kamu bikin hidupku linear ke arah baik.",
    "Kamu bukti kesabaran dan keteguhan.",
    "Kamu itu nilai tetap yang aku jaga.",
    "Kamu itu grafik yang nggak pernah turun di hatiku.",
    "Kamu bikin hariku penuh fungsi bahagia.",
    "Kamu angka favoritku.",
    "Kamu variabel yang selalu aku pertahankan.",
    "Kamu bikin aku terpaku kayak integral.",
    "Kamu itu perbandingan paling pas.",
    "Kamu itu deret naik: makin lama makin suka.",
    "Kamu tempatku kembali kalau capek.",
    "Kamu bikin aku merasa bernilai.",
    "Kamu bilangan yang selalu benar.",
    "Kamu bikin logikaku campur aduk tapi hati yakin.",
    "Kamu itu kecepatan tetap: selalu ada.",
    "Kamu grafik gelombang yang bikin aku deg-degan.",
    "Kamu bilangan yang tak bisa digantikan.",
    "Kamu pola yang selalu benar.",
    "Kamu itu probabilitas bahagia tertinggi.",
    "Kamu jawaban final dari perasaanku.",
    "Kamu itu titik optimum.",
    "Kamu bikin hidupku stabil tanpa rumus ribet.",
    "Kamu itu nilai yang cocok di persamaan hatiku.",
    "Kamu bukti kalau matematika juga bisa bikin baper."
];

function randomQuote() {
    const random = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[random];
}
